<h1>Index</h1>
<hr>
<?php
  foreach($this->view->dados as $indice => $produto) {
    echo $produto['id'] . ' - ' . $produto['descricao'] . ' - ' . $produto['preco'];
    echo '<br />'; 
  }

  // class A {
  //   public static function foo() {
  //     static::who();
  //   }

  //   public static function who() {
  //     echo __CLASS__."\n";
  //   }
  // }

  // class B extends A {
  //   public static function test() {
  //     A::foo();
  //     parent::foo();
  //     self::foo();
  //   }

  //   public static function who() {
  //     echo __CLASS__."\n";
  //   }
  // }

  // class C extends B {
  //   public static function who() {
  //     echo __CLASS__."\n";
  //   }
  // }

  // C::test();

  // class A {
  //   public static function who() {
  //     echo __CLASS__;
  //   }
  //   public static function test() {
  //     self::who();
  //   }
  // }

  // class B extends A {
  //   public static function who() {
  //     echo __CLASS__;
  //   }
  // }

  // B::test();

  // class A {
  //   public static function who() {
  //     echo __CLASS__;
  //   }
  //   public static function test() {
  //     static::who(); // Here comes Late Static Bindings
  //   }
  // }

  // class B extends A {
  //   public static function who() {
  //     echo __CLASS__;
  //   }
  // }

  // B::test();
?>